"""Initial deployment platform schema.

Revision ID: d691393699b0
Revises:
Create Date: 2026-05-02 01:58:02.468417
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d691393699b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "platform_owner",
                "admin",
                "developer",
                "viewer",
                name="userrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "teams",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_team_slug"),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index(
        op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_name"), "workspaces", ["name"], unique=False)
    op.create_index(
        op.f("ix_workspaces_organization_id"),
        "workspaces",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", name="apikeystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.create_index(
        op.f("ix_api_keys_workspace_id"), "api_keys", ["workspace_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"),
        "audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_workspace_id"), "audit_logs", ["workspace_id"], unique=False
    )
    op.create_table(
        "deployable_services",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(length=600), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "frontend",
                "backend",
                "worker",
                "api",
                name="servicetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "framework",
            sa.Enum(
                "nextjs",
                "fastapi",
                "node",
                "python",
                "other",
                name="serviceframework",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "healthy",
                "degraded",
                "offline",
                "unknown",
                name="servicestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("owner_team", sa.String(length=180), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_service_slug"),
    )
    op.create_index(
        op.f("ix_deployable_services_created_by"),
        "deployable_services",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_framework"),
        "deployable_services",
        ["framework"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_name"),
        "deployable_services",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_organization_id"),
        "deployable_services",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_owner_team"),
        "deployable_services",
        ["owner_team"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_service_type"),
        "deployable_services",
        ["service_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_slug"),
        "deployable_services",
        ["slug"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_status"),
        "deployable_services",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployable_services_team_id"),
        "deployable_services",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "workspace_members",
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "platform_owner",
                "admin",
                "developer",
                "viewer",
                "owner",
                "member",
                name="workspacerole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id", name="uq_workspace_member_user"),
    )
    op.create_index(
        op.f("ix_workspace_members_role"), "workspace_members", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_members_user_id"),
        "workspace_members",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_members_workspace_id"),
        "workspace_members",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "service_environments",
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "development",
                "staging",
                "production",
                "preview",
                name="environmentname",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("branch", sa.String(length=180), nullable=False),
        sa.Column("base_url", sa.String(length=600), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "healthy",
                "degraded",
                "offline",
                "unknown",
                name="servicestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("auto_deploy_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["deployable_services.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_id", "name", name="uq_service_environment_name"),
    )
    op.create_index(
        op.f("ix_service_environments_name"),
        "service_environments",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_environments_service_id"),
        "service_environments",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_environments_status"),
        "service_environments",
        ["status"],
        unique=False,
    )
    op.create_table(
        "deployments",
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=180), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "building",
                "deploying",
                "succeeded",
                "failed",
                "cancelled",
                "rolled_back",
                name="deploymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("triggered_by", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("rollback_source_deployment_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["service_environments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rollback_source_deployment_id"], ["deployments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["deployable_services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_branch"), "deployments", ["branch"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_commit_sha"), "deployments", ["commit_sha"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_environment_id"),
        "deployments",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployments_rollback_source_deployment_id"),
        "deployments",
        ["rollback_source_deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployments_service_id"), "deployments", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_status"), "deployments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_triggered_by"),
        "deployments",
        ["triggered_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployments_version"), "deployments", ["version"], unique=False
    )
    op.create_table(
        "environment_variables",
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("value_masked", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["service_environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "environment_id", "key", name="uq_environment_variable_key"
        ),
    )
    op.create_index(
        op.f("ix_environment_variables_environment_id"),
        "environment_variables",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environment_variables_key"),
        "environment_variables",
        ["key"],
        unique=False,
    )
    op.create_table(
        "health_checks",
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "healthy",
                "degraded",
                "offline",
                "unknown",
                name="servicestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["service_environments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_checks_environment_id"),
        "health_checks",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_checks_status"), "health_checks", ["status"], unique=False
    )
    op.create_table(
        "deployment_logs",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column(
            "level",
            sa.Enum("info", "warning", "error", name="loglevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("step", sa.String(length=120), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_logs_deployment_id"),
        "deployment_logs",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deployment_logs_level"), "deployment_logs", ["level"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=36), nullable=True),
        sa.Column("environment_id", sa.String(length=36), nullable=True),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="incidentseverity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "investigating",
                "resolved",
                name="incidentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["service_environments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["deployable_services.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_deployment_id"), "incidents", ["deployment_id"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_environment_id"),
        "incidents",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incidents_organization_id"),
        "incidents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incidents_service_id"), "incidents", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(op.f("ix_incidents_title"), "incidents", ["title"], unique=False)
    op.create_table(
        "incident_timeline_entries",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_timeline_entries_actor_id"),
        "incident_timeline_entries",
        ["actor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_timeline_entries_incident_id"),
        "incident_timeline_entries",
        ["incident_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_incident_timeline_entries_incident_id"),
        table_name="incident_timeline_entries",
    )
    op.drop_index(
        op.f("ix_incident_timeline_entries_actor_id"),
        table_name="incident_timeline_entries",
    )
    op.drop_table("incident_timeline_entries")
    op.drop_index(op.f("ix_incidents_title"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_service_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_environment_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_deployment_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_deployment_logs_level"), table_name="deployment_logs")
    op.drop_index(
        op.f("ix_deployment_logs_deployment_id"), table_name="deployment_logs"
    )
    op.drop_table("deployment_logs")
    op.drop_index(op.f("ix_health_checks_status"), table_name="health_checks")
    op.drop_index(op.f("ix_health_checks_environment_id"), table_name="health_checks")
    op.drop_table("health_checks")
    op.drop_index(
        op.f("ix_environment_variables_key"), table_name="environment_variables"
    )
    op.drop_index(
        op.f("ix_environment_variables_environment_id"),
        table_name="environment_variables",
    )
    op.drop_table("environment_variables")
    op.drop_index(op.f("ix_deployments_version"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_triggered_by"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_status"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_service_id"), table_name="deployments")
    op.drop_index(
        op.f("ix_deployments_rollback_source_deployment_id"), table_name="deployments"
    )
    op.drop_index(op.f("ix_deployments_environment_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_commit_sha"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_branch"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(
        op.f("ix_service_environments_status"), table_name="service_environments"
    )
    op.drop_index(
        op.f("ix_service_environments_service_id"), table_name="service_environments"
    )
    op.drop_index(
        op.f("ix_service_environments_name"), table_name="service_environments"
    )
    op.drop_table("service_environments")
    op.drop_index(
        op.f("ix_workspace_members_workspace_id"), table_name="workspace_members"
    )
    op.drop_index(op.f("ix_workspace_members_user_id"), table_name="workspace_members")
    op.drop_index(op.f("ix_workspace_members_role"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(
        op.f("ix_deployable_services_team_id"), table_name="deployable_services"
    )
    op.drop_index(
        op.f("ix_deployable_services_status"), table_name="deployable_services"
    )
    op.drop_index(op.f("ix_deployable_services_slug"), table_name="deployable_services")
    op.drop_index(
        op.f("ix_deployable_services_service_type"), table_name="deployable_services"
    )
    op.drop_index(
        op.f("ix_deployable_services_owner_team"), table_name="deployable_services"
    )
    op.drop_index(
        op.f("ix_deployable_services_organization_id"), table_name="deployable_services"
    )
    op.drop_index(op.f("ix_deployable_services_name"), table_name="deployable_services")
    op.drop_index(
        op.f("ix_deployable_services_framework"), table_name="deployable_services"
    )
    op.drop_index(
        op.f("ix_deployable_services_created_by"), table_name="deployable_services"
    )
    op.drop_table("deployable_services")
    op.drop_index(op.f("ix_audit_logs_workspace_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_workspace_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_organization_id"), table_name="workspaces")
    op.drop_index(op.f("ix_workspaces_name"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
